apiVersion: v1
kind: Service
metadata:
  name: ${{ values.serviceName }}
spec:
  selector:
    app: ${{ values.serviceName }}
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.serviceName }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.serviceName }}
  template:
    metadata:
      labels:
        app: ${{ values.serviceName }}
    spec:
      containers:
        - name: ${{ values.serviceName }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: bucket-creds
                  key: endpoint
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bucket-creds
                  key: bucketName
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bucket-creds
                  key: accessKey
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bucket-creds
                  key: secretKey
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.serviceName }}-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ${{ values.serviceName }}
            port:
              number: 80
